# Generated by Django 2.1.2 on 2019-01-10 12:59

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_noticia_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='contenido',
            field=tinymce.models.HTMLField(null=True, verbose_name='contenido'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='descripcion',
            field=models.TextField(max_length=1000, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Imagen'),
        ),
    ]
