# Generated by Django 2.1.2 on 2019-01-10 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0005_auto_20190110_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='descripcion',
        ),
    ]
