# Generated by Django 2.1.2 on 2019-01-10 14:52

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0006_remove_noticia_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='contenido',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='contenido'),
        ),
    ]
