# Generated by Django 2.1.2 on 2019-01-31 18:36

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0007_auto_20190110_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='contenido',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Contenido'),
        ),
    ]
