# Generated by Django 2.1.2 on 2018-12-13 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendario_curso',
            name='id_calendario',
        ),
        migrations.RemoveField(
            model_name='calendario_curso',
            name='id_curso',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='id_nivel',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='id_calendario',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='id_user',
        ),
        migrations.RemoveField(
            model_name='user_curso',
            name='id_curso',
        ),
        migrations.RemoveField(
            model_name='user_curso',
            name='id_user',
        ),
        migrations.DeleteModel(
            name='Calendario_curso',
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
        migrations.DeleteModel(
            name='Nivel',
        ),
        migrations.DeleteModel(
            name='Perfil',
        ),
        migrations.DeleteModel(
            name='User_curso',
        ),
    ]
