# Generated by Django 2.1.2 on 2018-12-13 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aula', '0005_calendario_curso'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('id_curso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='aula.Curso', verbose_name='Id curso')),
                ('id_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Id usuario')),
            ],
            options={
                'verbose_name': 'User_curso',
                'verbose_name_plural': 'User_cursos',
                'ordering': ['-created'],
            },
        ),
    ]
