# Generated by Django 2.1.2 on 2018-12-13 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0009_auto_20181213_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendario_curso',
            name='id_calendario',
        ),
        migrations.RemoveField(
            model_name='calendario_curso',
            name='id_curso',
        ),
        migrations.DeleteModel(
            name='Calendario_curso',
        ),
    ]
