# Generated by Django 2.1.2 on 2018-12-13 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0010_auto_20181213_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='id_calendario',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='aula.Calendario', verbose_name='Id Calendario'),
        ),
    ]
