# Generated by Django 2.1.2 on 2018-12-13 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0011_curso_id_calendario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='id_nivel',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='aula.Nivel', verbose_name='Id_nivel'),
        ),
    ]
