# Generated by Django 2.1.2 on 2018-12-13 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0012_auto_20181213_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='id_calendario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aula.Calendario', verbose_name='Id Calendario'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='id_nivel',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aula.Nivel', verbose_name='Id_nivel'),
        ),
    ]
