# Generated by Django 2.1.2 on 2018-12-13 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0013_auto_20181213_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='id_calendario',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='id_nivel',
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
    ]
