# Generated by Django 2.1.2 on 2018-12-13 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0014_auto_20181213_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('id_calendario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='aula.Calendario', verbose_name='Id Calendario')),
                ('id_nivel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='aula.Nivel', verbose_name='Id_nivel')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['-created'],
            },
        ),
    ]
