# Generated by Django 2.1.2 on 2018-12-13 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0017_user_asignatura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_asignatura',
            name='id_asignatura',
        ),
        migrations.RemoveField(
            model_name='user_asignatura',
            name='id_user',
        ),
        migrations.DeleteModel(
            name='Asignatura',
        ),
        migrations.DeleteModel(
            name='User_asignatura',
        ),
    ]
