# Generated by Django 2.1.2 on 2018-12-13 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0019_asignatura_user_asignatura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignatura',
            name='id_curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aula.Curso', verbose_name='Id_Curso'),
        ),
    ]
