# Generated by Django 2.1.2 on 2019-01-15 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0021_auto_20181213_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignatura',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='aula/asignaturas', verbose_name='Imagen'),
        ),
    ]
