# Generated by Django 2.1.2 on 2019-01-15 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0022_asignatura_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='siglas',
            field=models.CharField(default=123, max_length=10, verbose_name='Siglas'),
            preserve_default=False,
        ),
    ]
