# Generated by Django 2.1.2 on 2019-01-15 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0023_curso_siglas'),
    ]

    operations = [
        migrations.CreateModel(
            name='File_seccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='aula/files')),
                ('descripcion', models.TextField(blank=True, max_length=500, null=True, verbose_name='Descripción')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'File_seccion',
                'verbose_name_plural': 'File_seccion',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('id_asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aula.Asignatura', verbose_name='Asignatura')),
            ],
            options={
                'verbose_name': 'Sección',
                'verbose_name_plural': 'Secciones',
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='file_seccion',
            name='id_seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aula.Seccion', verbose_name='Seccion'),
        ),
    ]
