# Generated by Django 2.1.2 on 2019-01-15 17:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aula', '0024_auto_20190115_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignatura',
            name='alumnos',
            field=models.ManyToManyField(through='aula.User_asignatura', to=settings.AUTH_USER_MODEL),
        ),
    ]
