# Generated by Django 2.1.2 on 2019-01-16 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0025_asignatura_alumnos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seccion',
            old_name='id_asignatura',
            new_name='asignatura',
        ),
        migrations.RenameField(
            model_name='seccion',
            old_name='Titulo',
            new_name='titulo',
        ),
        migrations.AddField(
            model_name='asignatura',
            name='slug',
            field=models.SlugField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
