# Generated by Django 2.1.2 on 2019-01-21 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0027_auto_20190116_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='id_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL, verbose_name='Id usuario'),
        ),
    ]
