# Generated by Django 2.1.2 on 2019-01-22 07:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0028_auto_20190121_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='avatar',
            field=models.ImageField(blank=True, default='aula/static/imagenes/alumno.png', null=True, upload_to='registration/perfil', verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='id_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Id usuario'),
        ),
    ]
