# Generated by Django 2.1.2 on 2019-01-31 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0029_auto_20190122_0837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='id_calendario',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='id_calendario',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='tipo',
        ),
        migrations.DeleteModel(
            name='Calendario',
        ),
    ]
