# Generated by Django 2.1.2 on 2019-02-01 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0031_evento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evento',
            options={'ordering': ['-created'], 'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
        migrations.RemoveField(
            model_name='evento',
            name='fecha_fin',
        ),
    ]
