# Generated by Django 2.1.2 on 2019-02-01 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0032_auto_20190201_1946'),
    ]

    operations = [
        migrations.CreateModel(
            name='File_Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='aula/eventos/files')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aula.Evento', verbose_name='Evento')),
            ],
        ),
    ]
