# Generated by Django 2.1.2 on 2019-02-04 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0034_file_evento_alumno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_evento',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Alumno'),
        ),
        migrations.AlterField(
            model_name='file_evento',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fileEventos', to='aula.Evento', verbose_name='Evento'),
        ),
    ]
