# Generated by Django 2.1.2 on 2019-01-14 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0021_auto_20181213_1248'),
        ('foro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foro',
            name='id_asignatura',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='aula.Asignatura', verbose_name='id_Asignatura'),
            preserve_default=False,
        ),
    ]
